---
- name: install apache
  yum:
    name: httpd
    state: present

- name: enable apache at boot
  service:
    name: httpd
    enabled: true

- name: start apache
  service:
    name: httpd
    state: started
